"""empty message

Revision ID: 0ffc85023d42
Revises: 434488e1a305
Create Date: 2016-07-07 14:53:43.771509

"""

# revision identifiers, used by Alembic.
revision = '0ffc85023d42'
down_revision = '434488e1a305'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
