"""empty message

Revision ID: 1598401813d0
Revises: 56905f53af9d
Create Date: 2015-06-12 12:12:17.300359

"""

# revision identifiers, used by Alembic.
revision = '1598401813d0'
down_revision = '56905f53af9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voucher_vouchers', sa.Column('code', sa.String(length=20), nullable=True))
    op.drop_column('voucher_vouchers', 'coded')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voucher_vouchers', sa.Column('coded', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('voucher_vouchers', 'code')
    ### end Alembic commands ###
