"""empty message

Revision ID: 2270ad794153
Revises: a755e18b148
Create Date: 2015-06-12 12:07:41.855425

"""

# revision identifiers, used by Alembic.
revision = '2270ad794153'
down_revision = 'a755e18b148'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
