"""empty message

Revision ID: 2fcde1cbe141
Revises: b1a5f3a15137
Create Date: 2017-01-26 10:18:02.021739

"""

# revision identifiers, used by Alembic.
revision = '2fcde1cbe141'
down_revision = 'b1a5f3a15137'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_code', sa.Column('ft_row_id', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ref_code', 'ft_row_id')
    ### end Alembic commands ###
