"""empty message

Revision ID: 30a2dfa34a43
Revises: 484651bfac87
Create Date: 2015-06-09 15:05:39.585908

"""

# revision identifiers, used by Alembic.
revision = '30a2dfa34a43'
down_revision = '484651bfac87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
