"""empty message

Revision ID: 32b08015e6e
Revises: 30a2dfa34a43
Create Date: 2015-06-09 15:15:58.348907

"""

# revision identifiers, used by Alembic.
revision = '32b08015e6e'
down_revision = '30a2dfa34a43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
