"""empty message

Revision ID: 465d1104bfb8
Revises: 32b08015e6e
Create Date: 2015-06-11 08:52:29.030935

"""

# revision identifiers, used by Alembic.
revision = '465d1104bfb8'
down_revision = '32b08015e6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voucher_vouchers', sa.Column('flow_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voucher_vouchers', 'flow_id')
    ### end Alembic commands ###
