"""empty message

Revision ID: 484651bfac87
Revises: None
Create Date: 2015-06-09 11:53:38.428517

"""

# revision identifiers, used by Alembic.
revision = '484651bfac87'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
