"""empty message

Revision ID: 48fc79193cf2
Revises: 94235923a509
Create Date: 2016-07-11 14:42:28.082772

"""

# revision identifiers, used by Alembic.
revision = '48fc79193cf2'
down_revision = '94235923a509'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fusion_table_flows', sa.Column('email', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fusion_table_flows', 'email')
    ### end Alembic commands ###
