"""empty message

Revision ID: 56905f53af9d
Revises: 2270ad794153
Create Date: 2015-06-12 12:10:41.882163

"""

# revision identifiers, used by Alembic.
revision = '56905f53af9d'
down_revision = '2270ad794153'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voucher_vouchers', sa.Column('coded', sa.String(length=20), nullable=True))
    op.drop_column('voucher_vouchers', 'code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voucher_vouchers', sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.drop_column('voucher_vouchers', 'coded')
    ### end Alembic commands ###
