"""empty message

Revision ID: 66c5e17835a0
Revises: 48fc79193cf2
Create Date: 2016-07-11 14:42:35.705112

"""

# revision identifiers, used by Alembic.
revision = '66c5e17835a0'
down_revision = '48fc79193cf2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
