"""empty message

Revision ID: 81af3f99f387
Revises: 74166be94fd8
Create Date: 2017-10-12 08:52:03.150095

"""

# revision identifiers, used by Alembic.
revision = '81af3f99f387'
down_revision = '74166be94fd8'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group', sa.String(), nullable=True))
    op.add_column('user', sa.Column('group_slug', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'group_slug')
    op.drop_column('user', 'group')
    ### end Alembic commands ###
