"""empty message

Revision ID: 94235923a509
Revises: 5a31bc768352
Create Date: 2016-07-11 10:22:32.763269

"""

# revision identifiers, used by Alembic.
revision = '94235923a509'
down_revision = '5a31bc768352'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'fusion_table_flows', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fusion_table_flows', type_='unique')
    ### end Alembic commands ###
