"""empty message

Revision ID: a755e18b148
Revises: 465d1104bfb8
Create Date: 2015-06-11 08:56:03.760770

"""

# revision identifiers, used by Alembic.
revision = 'a755e18b148'
down_revision = '465d1104bfb8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
