"""empty message

Revision ID: b50f86c87339
Revises: 0ffc85023d42
Create Date: 2016-07-07 14:59:14.864651

"""

# revision identifiers, used by Alembic.
revision = 'b50f86c87339'
down_revision = '0ffc85023d42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
