"""empty message

Revision ID: dab42a6879dd
Revises: 706b59f6019c
Create Date: 2017-08-22 13:55:56.927686

"""

# revision identifiers, used by Alembic.
revision = 'dab42a6879dd'
down_revision = '706b59f6019c'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'country')
    ### end Alembic commands ###
