"""empty message

Revision ID: f78243468d0e
Revises: 29f7009fa84a
Create Date: 2016-12-19 17:04:52.576384

"""

# revision identifiers, used by Alembic.
revision = 'f78243468d0e'
down_revision = '29f7009fa84a'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rapidpro_uuid', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral')
    ### end Alembic commands ###
